from django.contrib import admin

from django.db import models

from django.db import models



class TouristSite(models.Model):
	name= models.CharField(max_length=200)
	town= models.CharField(max_length=200)
	country= models.CharField(max_length=200)
	last_modified= models.DateTimeField(auto_now=True)
	SITE_CHOICES=(('hotel', 'Hotel'), ('park', 'Park'), ('forest_reserve', 'Forest Reserve'), ('wetland', 'Wetland'), ('heritage_site', 'Heritage Site'),('castle','Fort/Castle'),('museum', 'Museum'))
	site_type=models.CharField(max_length=60, choices=SITE_CHOICES)
	REGION_CHOICES=(('greater_accra', 'Greater Accra'), ('northern', 'Northern'), ('brong_ahafo', 'Brong Ahafo'),
	('central', 'Central'), ('upper_east', 'Upper East'),
	('upper_west','Upper West'),('ashanti', 'Ashanti'),('volta','Volta'),('western', 'Western'),('eastern', 'Eastern'))
	region= models.CharField(max_length=60, choices=REGION_CHOICES)
	
	COUNTRIES = (
    ('AFG', ('Afghanistan')), 
    ('ALA', ('Aland Islands')),
    ('ALB', ('Albania')),
    ('DZA', ('Algeria')),
    ('ASM', ('American Samoa')),
    ('AND', ('Andorra')),
    ('AGO', ('Angola')),
    ('AIA', ('Anguilla')),
    ('ATG', ('Antigua and Barbuda')),
    ('ARG', ('Argentina')),
    ('ARM', ('Armenia')),
    ('ABW', ('Aruba')),
    ('AUS', ('Australia')),
    ('AUT', ('Austria')),
    ('AZE', ('Azerbaijan')),
    ('BHS', ('Bahamas')),
    ('BHR', ('Bahrain')),
    ('BGD', ('Bangladesh')),
    ('BRB', ('Barbados')),
    ('BLR', ('Belarus')),
    ('BEL', ('Belgium')),
    ('BLZ', ('Belize')),
    ('BEN', ('Benin')),
    ('BMU', ('Bermuda')),
    ('BTN', ('Bhutan')),
    ('BOL', ('Bolivia')),
    ('BIH', ('Bosnia and Herzegovina')),
    ('BWA', ('Botswana')),
    ('BRA', ('Brazil')),
    ('VGB', ('British Virgin Islands')),
    ('BRN', ('Brunei Darussalam')),
    ('BGR', ('Bulgaria')),
    ('BFA', ('Burkina Faso')),
    ('BDI', ('Burundi')),
    ('KHM', ('Cambodia')),
    ('CMR', ('Cameroon')),
    ('CAN', ('Canada')),
    ('CPV', ('Cape Verde')),
    ('CYM', ('Cayman Islands')),
    ('CAF', ('Central African Republic')),
    ('TCD', ('Chad')),
    ('CIL', ('Channel Islands')),
    ('CHL', ('Chile')),
    ('CHN', ('China')),
    ('HKG', ('China - Hong Kong')),
    ('MAC', ('China - Macao')),
    ('COL', ('Colombia')),
    ('COM', ('Comoros')),
    ('COG', ('Congo')),
    ('COK', ('Cook Islands')),
    ('CRI', ('Costa Rica')),
    ('CIV', ('Cote d\'Ivoire')),
    ('HRV', ('Croatia')),
    ('CUB', ('Cuba')),
    ('CYP', ('Cyprus')),
    ('CZE', ('Czech Republic')),
    ('PRK', ('Democratic People\'s Republic of Korea')),
    ('COD', ('Democratic Republic of the Congo')),
    ('DNK', ('Denmark')),
    ('DJI', ('Djibouti')),
    ('DMA', ('Dominica')),
    ('DOM', ('Dominican Republic')),
    ('ECU', ('Ecuador')),
    ('EGY', ('Egypt')),
    ('SLV', ('El Salvador')),
    ('GNQ', ('Equatorial Guinea')),
    ('ERI', ('Eritrea')),
    ('EST', ('Estonia')),
    ('ETH', ('Ethiopia')),
    ('FRO', ('Faeroe Islands')),
    ('FLK', ('Falkland Islands (Malvinas)')),
    ('FJI', ('Fiji')),
    ('FIN', ('Finland')),
    ('FRA', ('France')),
    ('GUF', ('French Guiana')),
    ('PYF', ('French Polynesia')),
    ('GAB', ('Gabon')),
    ('GMB', ('Gambia')),
    ('GEO', ('Georgia')),
    ('DEU', ('Germany')),
    ('GHA', ('Ghana')),
    ('GIB', ('Gibraltar')),
    ('GRC', ('Greece')),
    ('GRL', ('Greenland')),
    ('GRD', ('Grenada')),
    ('GLP', ('Guadeloupe')),
    ('GUM', ('Guam')),
    ('GTM', ('Guatemala')),
    ('GGY', ('Guernsey')),
    ('GIN', ('Guinea')),
    ('GNB', ('Guinea-Bissau')),
    ('GUY', ('Guyana')),
    ('HTI', ('Haiti')),
    ('VAT', ('Holy See (Vatican City)')),
    ('HND', ('Honduras')),
    ('HUN', ('Hungary')),
    ('ISL', ('Iceland')),
    ('IND', ('India')),
    ('IDN', ('Indonesia')),
    ('IRN', ('Iran')),
    ('IRQ', ('Iraq')),
    ('IRL', ('Ireland')),
    ('IMN', ('Isle of Man')),
    ('ISR', ('Israel')),
    ('ITA', ('Italy')),
    ('JAM', ('Jamaica')),
    ('JPN', ('Japan')),
    ('JEY', ('Jersey')),
    ('JOR', ('Jordan')),
    ('KAZ', ('Kazakhstan')),
    ('KEN', ('Kenya')),
    ('KIR', ('Kiribati')),
    ('KWT', ('Kuwait')),
    ('KGZ', ('Kyrgyzstan')),
    ('LAO', ('Lao People\'s Democratic Republic')),
    ('LVA', ('Latvia')),
    ('LBN', ('Lebanon')),
    ('LSO', ('Lesotho')),
    ('LBR', ('Liberia')),
    ('LBY', ('Libyan Arab Jamahiriya')),
    ('LIE', ('Liechtenstein')),
    ('LTU', ('Lithuania')),
    ('LUX', ('Luxembourg')),
    ('MKD', ('Macedonia')),
    ('MDG', ('Madagascar')),
    ('MWI', ('Malawi')),
    ('MYS', ('Malaysia')),
    ('MDV', ('Maldives')),
    ('MLI', ('Mali')),
    ('MLT', ('Malta')),
    ('MHL', ('Marshall Islands')),
    ('MTQ', ('Martinique')),
    ('MRT', ('Mauritania')),
    ('MUS', ('Mauritius')),
    ('MYT', ('Mayotte')),
    ('MEX', ('Mexico')),
    ('FSM', ('Micronesia, Federated States of')),
    ('MCO', ('Monaco')),
    ('MNG', ('Mongolia')),
    ('MNE', ('Montenegro')),
    ('MSR', ('Montserrat')),
    ('MAR', ('Morocco')),
    ('MOZ', ('Mozambique')),
    ('MMR', ('Myanmar')),
    ('NAM', ('Namibia')),
    ('NRU', ('Nauru')),
    ('NPL', ('Nepal')),
    ('NLD', ('Netherlands')),
    ('ANT', ('Netherlands Antilles')),
    ('NCL', ('New Caledonia')),
    ('NZL', ('New Zealand')),
    ('NIC', ('Nicaragua')),
    ('NER', ('Niger')),
    ('NGA', ('Nigeria')),
    ('NIU', ('Niue')),
    ('NFK', ('Norfolk Island')),
    ('MNP', ('Northern Mariana Islands')),
    ('NOR', ('Norway')),
    ('PSE', ('Occupied Palestinian Territory')),
    ('OMN', ('Oman')),
    ('PAK', ('Pakistan')),
    ('PLW', ('Palau')),
    ('PAN', ('Panama')),
    ('PNG', ('Papua New Guinea')),
    ('PRY', ('Paraguay')),
    ('PER', ('Peru')),
    ('PHL', ('Philippines')),
    ('PCN', ('Pitcairn')),
    ('POL', ('Poland')),
    ('PRT', ('Portugal')),
    ('PRI', ('Puerto Rico')),
    ('QAT', ('Qatar')),
    ('KOR', ('Republic of Korea')),
    ('MDA', ('Republic of Moldova')),
    ('REU', ('Reunion')),
    ('ROU', ('Romania')),
    ('RUS', ('Russian Federation')),
    ('RWA', ('Rwanda')),
    ('BLM', ('Saint-Barthelemy')),
    ('SHN', ('Saint Helena')),
    ('KNA', ('Saint Kitts and Nevis')),
    ('LCA', ('Saint Lucia')),
    ('MAF', ('Saint-Martin (French part)')),
    ('SPM', ('Saint Pierre and Miquelon')),
    ('VCT', ('Saint Vincent and the Grenadines')),
    ('WSM', ('Samoa')),
    ('SMR', ('San Marino')),
    ('STP', ('Sao Tome and Principe')),
    ('SAU', ('Saudi Arabia')),
    ('SEN', ('Senegal')),
    ('SRB', ('Serbia')),
    ('SYC', ('Seychelles')),
    ('SLE', ('Sierra Leone')),
    ('SGP', ('Singapore')),
    ('SVK', ('Slovakia')),
    ('SVN', ('Slovenia')),
    ('SLB', ('Solomon Islands')),
    ('SOM', ('Somalia')),
    ('ZAF', ('South Africa')),
    ('ssd', ('South Sudan')),
    ('ESP', ('Spain')),
    ('LKA', ('Sri Lanka')),
    ('SDN', ('Sudan')),
    ('SUR', ('Suriname')),
    ('SJM', ('Svalbard and Jan Mayen Islands')),
    ('SWZ', ('Swaziland')),
    ('SWE', ('Sweden')),
    ('CHE', ('Switzerland')),
    ('SYR', ('Syrian Arab Republic')),
    ('TJK', ('Tajikistan')),
    ('THA', ('Thailand')),
    ('TLS', ('Timor-Leste')),
    ('TGO', ('Togo')),
    ('TKL', ('Tokelau')),
    ('TON', ('Tonga')),
    ('TTO', ('Trinidad and Tobago')),
    ('TUN', ('Tunisia')),
    ('TUR', ('Turkey')),
    ('TKM', ('Turkmenistan')),
    ('TCA', ('Turks and Caicos Islands')),
    ('TUV', ('Tuvalu')),
    ('UGA', ('Uganda')),
    ('UKR', ('Ukraine')),
    ('ARE', ('United Arab Emirates')),
    ('GBR', ('United Kingdom')),
    ('TZA', ('United Republic of Tanzania')),
    ('USA', ('United States of America')),
    ('VIR', ('United States Virgin Islands')),
    ('URY', ('Uruguay')),
    ('UZB', ('Uzbekistan')),
    ('VUT', ('Vanuatu')),
    ('VEN', ('Venezuela (Bolivarian Republic of)')),
    ('VNM', ('Viet Nam')),
    ('WLF', ('Wallis and Futuna Islands')),
    ('ESH', ('Western Sahara')),
    ('YEM', ('Yemen')),
    ('ZMB', ('Zambia')),
    ('ZWE', ('Zimbabwe')),
)
	country = models.CharField(max_length=60, choices=COUNTRIES)
	def __unicode__(self):
		return self.name


class Review(models.Model):
	review_title = models.ForeignKey('TouristSite')
	review_body= models.TextField()
	review_author= models.CharField(max_length=60)
	review_created= models.DateTimeField(auto_now=True)
	review_updated= models.DateTimeField(auto_now_add=True)
	def title_first_ten(self):
		return self.title[:10]
        def __unicode__(self):
		return self.review_author
	
class MyVillage(models.Model):
	v_name= models.CharField('Village name', max_length=30)
	v_region= models.CharField('Region', max_length=30)
	v_nearto= models.CharField('Nearest city/town', max_length=30)
	v_attraction1= models.CharField('Attraction 1', blank=True, max_length=50)
	v_attraction2= models.CharField('Attraction 2', blank=True, max_length=50)
	v_attraction3= models.CharField('Attraction 3', blank=True, max_length=50)
	v_attraction4= models.CharField('Attraction 4', blank=True, max_length=50)
	v_attraction5= models.CharField('Attraction 5', blank=True, max_length=50)
	v_review= models.TextField('Village Review', blank=True, )
	v_added=models.DateTimeField('Date added', auto_now=True)
	v_updated=models.DateTimeField('Last updated', auto_now_add=True)
	REGION_CHOICES=(('greater_accra', 'Greater Accra'), ('northern', 'Northern'), ('brong_ahafo', 'Brong Ahafo'),
	('central', 'Central'), ('upper_east', 'Upper East'),
	('upper_west','Upper West'),('ashanti', 'Ashanti'),('volta','Volta'),('western', 'Western'),('eastern', 'Eastern'))
	v_region= models.CharField(max_length=60, choices=REGION_CHOICES)
	
	COUNTRIES = (
    ('AFG', ('Afghanistan')), 
    ('ALA', ('Aland Islands')),
    ('ALB', ('Albania')),
    ('DZA', ('Algeria')),
    ('ASM', ('American Samoa')),
    ('AND', ('Andorra')),
    ('AGO', ('Angola')),
    ('AIA', ('Anguilla')),
    ('ATG', ('Antigua and Barbuda')),
    ('ARG', ('Argentina')),
    ('ARM', ('Armenia')),
    ('ABW', ('Aruba')),
    ('AUS', ('Australia')),
    ('AUT', ('Austria')),
    ('AZE', ('Azerbaijan')),
    ('BHS', ('Bahamas')),
    ('BHR', ('Bahrain')),
    ('BGD', ('Bangladesh')),
    ('BRB', ('Barbados')),
    ('BLR', ('Belarus')),
    ('BEL', ('Belgium')),
    ('BLZ', ('Belize')),
    ('BEN', ('Benin')),
    ('BMU', ('Bermuda')),
    ('BTN', ('Bhutan')),
    ('BOL', ('Bolivia')),
    ('BIH', ('Bosnia and Herzegovina')),
    ('BWA', ('Botswana')),
    ('BRA', ('Brazil')),
    ('VGB', ('British Virgin Islands')),
    ('BRN', ('Brunei Darussalam')),
    ('BGR', ('Bulgaria')),
    ('BFA', ('Burkina Faso')),
    ('BDI', ('Burundi')),
    ('KHM', ('Cambodia')),
    ('CMR', ('Cameroon')),
    ('CAN', ('Canada')),
    ('CPV', ('Cape Verde')),
    ('CYM', ('Cayman Islands')),
    ('CAF', ('Central African Republic')),
    ('TCD', ('Chad')),
    ('CIL', ('Channel Islands')),
    ('CHL', ('Chile')),
    ('CHN', ('China')),
    ('HKG', ('China - Hong Kong')),
    ('MAC', ('China - Macao')),
    ('COL', ('Colombia')),
    ('COM', ('Comoros')),
    ('COG', ('Congo')),
    ('COK', ('Cook Islands')),
    ('CRI', ('Costa Rica')),
    ('CIV', ('Cote d\'Ivoire')),
    ('HRV', ('Croatia')),
    ('CUB', ('Cuba')),
    ('CYP', ('Cyprus')),
    ('CZE', ('Czech Republic')),
    ('PRK', ('Democratic People\'s Republic of Korea')),
    ('COD', ('Democratic Republic of the Congo')),
    ('DNK', ('Denmark')),
    ('DJI', ('Djibouti')),
    ('DMA', ('Dominica')),
    ('DOM', ('Dominican Republic')),
    ('ECU', ('Ecuador')),
    ('EGY', ('Egypt')),
    ('SLV', ('El Salvador')),
    ('GNQ', ('Equatorial Guinea')),
    ('ERI', ('Eritrea')),
    ('EST', ('Estonia')),
    ('ETH', ('Ethiopia')),
    ('FRO', ('Faeroe Islands')),
    ('FLK', ('Falkland Islands (Malvinas)')),
    ('FJI', ('Fiji')),
    ('FIN', ('Finland')),
    ('FRA', ('France')),
    ('GUF', ('French Guiana')),
    ('PYF', ('French Polynesia')),
    ('GAB', ('Gabon')),
    ('GMB', ('Gambia')),
    ('GEO', ('Georgia')),
    ('DEU', ('Germany')),
    ('GHA', ('Ghana')),
    ('GIB', ('Gibraltar')),
    ('GRC', ('Greece')),
    ('GRL', ('Greenland')),
    ('GRD', ('Grenada')),
    ('GLP', ('Guadeloupe')),
    ('GUM', ('Guam')),
    ('GTM', ('Guatemala')),
    ('GGY', ('Guernsey')),
    ('GIN', ('Guinea')),
    ('GNB', ('Guinea-Bissau')),
    ('GUY', ('Guyana')),
    ('HTI', ('Haiti')),
    ('VAT', ('Holy See (Vatican City)')),
    ('HND', ('Honduras')),
    ('HUN', ('Hungary')),
    ('ISL', ('Iceland')),
    ('IND', ('India')),
    ('IDN', ('Indonesia')),
    ('IRN', ('Iran')),
    ('IRQ', ('Iraq')),
    ('IRL', ('Ireland')),
    ('IMN', ('Isle of Man')),
    ('ISR', ('Israel')),
    ('ITA', ('Italy')),
    ('JAM', ('Jamaica')),
    ('JPN', ('Japan')),
    ('JEY', ('Jersey')),
    ('JOR', ('Jordan')),
    ('KAZ', ('Kazakhstan')),
    ('KEN', ('Kenya')),
    ('KIR', ('Kiribati')),
    ('KWT', ('Kuwait')),
    ('KGZ', ('Kyrgyzstan')),
    ('LAO', ('Lao People\'s Democratic Republic')),
    ('LVA', ('Latvia')),
    ('LBN', ('Lebanon')),
    ('LSO', ('Lesotho')),
    ('LBR', ('Liberia')),
    ('LBY', ('Libyan Arab Jamahiriya')),
    ('LIE', ('Liechtenstein')),
    ('LTU', ('Lithuania')),
    ('LUX', ('Luxembourg')),
    ('MKD', ('Macedonia')),
    ('MDG', ('Madagascar')),
    ('MWI', ('Malawi')),
    ('MYS', ('Malaysia')),
    ('MDV', ('Maldives')),
    ('MLI', ('Mali')),
    ('MLT', ('Malta')),
    ('MHL', ('Marshall Islands')),
    ('MTQ', ('Martinique')),
    ('MRT', ('Mauritania')),
    ('MUS', ('Mauritius')),
    ('MYT', ('Mayotte')),
    ('MEX', ('Mexico')),
    ('FSM', ('Micronesia, Federated States of')),
    ('MCO', ('Monaco')),
    ('MNG', ('Mongolia')),
    ('MNE', ('Montenegro')),
    ('MSR', ('Montserrat')),
    ('MAR', ('Morocco')),
    ('MOZ', ('Mozambique')),
    ('MMR', ('Myanmar')),
    ('NAM', ('Namibia')),
    ('NRU', ('Nauru')),
    ('NPL', ('Nepal')),
    ('NLD', ('Netherlands')),
    ('ANT', ('Netherlands Antilles')),
    ('NCL', ('New Caledonia')),
    ('NZL', ('New Zealand')),
    ('NIC', ('Nicaragua')),
    ('NER', ('Niger')),
    ('NGA', ('Nigeria')),
    ('NIU', ('Niue')),
    ('NFK', ('Norfolk Island')),
    ('MNP', ('Northern Mariana Islands')),
    ('NOR', ('Norway')),
    ('PSE', ('Occupied Palestinian Territory')),
    ('OMN', ('Oman')),
    ('PAK', ('Pakistan')),
    ('PLW', ('Palau')),
    ('PAN', ('Panama')),
    ('PNG', ('Papua New Guinea')),
    ('PRY', ('Paraguay')),
    ('PER', ('Peru')),
    ('PHL', ('Philippines')),
    ('PCN', ('Pitcairn')),
    ('POL', ('Poland')),
    ('PRT', ('Portugal')),
    ('PRI', ('Puerto Rico')),
    ('QAT', ('Qatar')),
    ('KOR', ('Republic of Korea')),
    ('MDA', ('Republic of Moldova')),
    ('REU', ('Reunion')),
    ('ROU', ('Romania')),
    ('RUS', ('Russian Federation')),
    ('RWA', ('Rwanda')),
    ('BLM', ('Saint-Barthelemy')),
    ('SHN', ('Saint Helena')),
    ('KNA', ('Saint Kitts and Nevis')),
    ('LCA', ('Saint Lucia')),
    ('MAF', ('Saint-Martin (French part)')),
    ('SPM', ('Saint Pierre and Miquelon')),
    ('VCT', ('Saint Vincent and the Grenadines')),
    ('WSM', ('Samoa')),
    ('SMR', ('San Marino')),
    ('STP', ('Sao Tome and Principe')),
    ('SAU', ('Saudi Arabia')),
    ('SEN', ('Senegal')),
    ('SRB', ('Serbia')),
    ('SYC', ('Seychelles')),
    ('SLE', ('Sierra Leone')),
    ('SGP', ('Singapore')),
    ('SVK', ('Slovakia')),
    ('SVN', ('Slovenia')),
    ('SLB', ('Solomon Islands')),
    ('SOM', ('Somalia')),
    ('ZAF', ('South Africa')),
    ('ssd', ('South Sudan')),
    ('ESP', ('Spain')),
    ('LKA', ('Sri Lanka')),
    ('SDN', ('Sudan')),
    ('SUR', ('Suriname')),
    ('SJM', ('Svalbard and Jan Mayen Islands')),
    ('SWZ', ('Swaziland')),
    ('SWE', ('Sweden')),
    ('CHE', ('Switzerland')),
    ('SYR', ('Syrian Arab Republic')),
    ('TJK', ('Tajikistan')),
    ('THA', ('Thailand')),
    ('TLS', ('Timor-Leste')),
    ('TGO', ('Togo')),
    ('TKL', ('Tokelau')),
    ('TON', ('Tonga')),
    ('TTO', ('Trinidad and Tobago')),
    ('TUN', ('Tunisia')),
    ('TUR', ('Turkey')),
    ('TKM', ('Turkmenistan')),
    ('TCA', ('Turks and Caicos Islands')),
    ('TUV', ('Tuvalu')),
    ('UGA', ('Uganda')),
    ('UKR', ('Ukraine')),
    ('ARE', ('United Arab Emirates')),
    ('GBR', ('United Kingdom')),
    ('TZA', ('United Republic of Tanzania')),
    ('USA', ('United States of America')),
    ('VIR', ('United States Virgin Islands')),
    ('URY', ('Uruguay')),
    ('UZB', ('Uzbekistan')),
    ('VUT', ('Vanuatu')),
    ('VEN', ('Venezuela (Bolivarian Republic of)')),
    ('VNM', ('Viet Nam')),
    ('WLF', ('Wallis and Futuna Islands')),
    ('ESH', ('Western Sahara')),
    ('YEM', ('Yemen')),
    ('ZMB', ('Zambia')),
    ('ZWE', ('Zimbabwe')),
)
	country = models.CharField(max_length=60, choices=COUNTRIES)
	def __unicode__(self):
		return self.v_name
	

class ReviewInline(admin.TabularInline):
        model = Review

class TouristSiteAdmin(admin.ModelAdmin):
	list_display = ('name', 'town', 'region', 'last_modified')
	search_fields = ('name', 'region', 'description')
	list_filter = ('name','last_modified')
	inlines = [ReviewInline]


admin.site.register(TouristSite, TouristSiteAdmin)
admin.site.register(MyVillage)

