from django.conf.urls.defaults import *
from django.contrib import admin


urlpatterns = patterns('',
	url(r'^$', 'i-kijiji.views.welcome'),
	url(r'^sitelist/$', 'i-kijiji.views.site_list'),
	url(r'^selectsite/$', 'i-kijiji.views.region_list'),
	url(r'^selectvillage/$', 'i-kijiji.views.v_region_list'),
	url(r'^northern/$', 'i-kijiji.views.northern_list'),
	url(r'^v_northern/$', 'i-kijiji.views.v_northern_list'),
	url(r'^uer/$', 'i-kijiji.views.uer_list'),
	url(r'^v_uer/$', 'i-kijiji.views.v_uer_list'),
	url(r'^uwr/$', 'i-kijiji.views.uwr_list'),
	url(r'^v_uwr/$', 'i-kijiji.views.v_uwr_list'),
	url(r'^volta/$', 'i-kijiji.views.volta_list'),
	url(r'^v_volta/$', 'i-kijiji.views.v_volta_list'),
	url(r'^ga/$', 'i-kijiji.views.ga_list'),
	url(r'^v_ga/$', 'i-kijiji.views.v_ga_list'),
	url(r'^ba/$', 'i-kijiji.views.ba_list'),
	url(r'^v_ba/$', 'i-kijiji.views.v_ba_list'),
	url(r'^ashanti/$', 'i-kijiji.views.ashanti_list'),
	url(r'^v_ashanti/$', 'i-kijiji.views.v_ashanti_list'),
	url(r'^eastern/$', 'i-kijiji.views.eastern_list'),
	url(r'^v_eastern/$', 'i-kijiji.views.v_eastern_list'),
	url(r'^western/$', 'i-kijiji.views.western_list'),
	url(r'^v_western/$', 'i-kijiji.views.v_western_list'),
	url(r'^central/$', 'i-kijiji.views.central_list'),
	url(r'^v_central/$', 'i-kijiji.views.v_central_list'),

	url(r'^sitedetail/(?P<id>\d+)/$','i-kijiji.views.site_detail'),
	url(r'^villagedetail/(?P<id>\d+)/$','i-kijiji.views.village_detail'),
	
	url(r'^reviewsite/(?P<id>\d+)/((?P<showReviews>.*)/)?$','i-kijiji.views.detail_review'),
	url(r'^login/$', 'i-kijiji.views.login'),	
	url(r'^register/$', 'i-kijiji.views.register'),
	url(r'^welcome/$', 'i-kijiji.views.welcome'),
	url(r'^myvillage/$', 'i-kijiji.views.my_village'),
	url(r'^features/$', 'i-kijiji.views.feature_list'),
)
